---
- hosts: localhost
  connection: local
  # as root
  become: true
  # as other user
#  become_user: p4810

  pre_tasks:
    # sudo apt update
    - name: pre-run | update package cache (debian, etc)
      tags: always
      apt: update_cache=yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

  tasks:
#    # instaling htop package
#    - name: install htop
#      package:
#        name:
#          - htop
#          - tmux
#          - nano
#          - vim-nox

    - name: copy .bashrc file
      copy:
        src: files/bashrc
        dest: "/home/p4810/.bashrc"
        owner: p4810
        group: p4810

    - name: add user velociraptor
      user:
        name: velociraptor
        system: yes

    - name: set up sudo for ansible user
      copy:
        src: files/sudoer_velociraptor
        dest: /etc/sudoers.d/velociraptor
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
#      become: true
      cron:
        name: ansible auto-provision
        user: velociraptor
        minute: "*/10"
        # >   sudo crontab -u velociraptor -l
        # >   sudo journalctl | grep CRON | grep ansible-pull
        job: ansible-pull -o -U https://github.com/pdamaszk/ansible.git >> /home/velociraptor/logfile.log 2>&1
#        job: ansible-pull -o -U https://github.com/pdamaszk/ansible.git
## task to complete before running roles
#- hosts: all
#  tags: slways
#  become: true
#  pre_task:
#    # sudo pacman update
#    - name: pre-run | update package cache (arch)
#      tags: always
#      pacman: update_cache=yes
#      when: ansible_distribution == "Archlinux"
#
#    # sudo apt update
#    - name: pre-run | update package cache (debian, etc)
#      tags: always
#      apt: update_cache=yes
#      when: ansible_distribution in ["Debian", "Ubuntu"]
#
## run roles
#- hosts: all
#  tags: base
#  become: true
#  roles:
#    - base
#
#- hosts: workstation
#  tags: workstation
#  become: true
#  roles:
#    - workstation
#
#- hosts: server
#  tags: server
#  become: true
#  roles:
#    - server
